# Default values for rate-limit-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: softonic/ip-blocker
  pullPolicy: IfNotPresent
  tag: 0.0.1-dev

imageFullnameOverride: null

imagePullSecrets:
- name: registry.softonic.io
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

resources: {}
#  limits:
#    cpu: 100m
#    memory: 30Mi
#  requests:
#    cpu: 100m
#    memory: 20Mi

args:
 - -project=kubertonic
 - -policy=global-loadbalancer-rules
 - -cacert=/etc/ssl/ca/cacert.pem

extraVolumes:
  - name: cacert
    secret:
      secretName: elastic-ca-cert

extraVolumeMounts:
  - mountPath: /etc/ssl/ca/
    name: cacert



elastic:
  address: "https://host.docker.internal:9200"
