# Default values for rate-limit-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: softonic/ip-blocker
  pullPolicy: IfNotPresent
  tag: 0.0.1-dev

imageFullnameOverride: null

imagePullSecrets:
- name: registry.softonic.io
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

resources: {}
#  limits:
#    cpu: 100m
#    memory: 30Mi
#  requests:
#    cpu: 100m
#    memory: 20Mi

args: []
extraVolumes: []

extraVolumeMounts: []

elastic:
  

elasticSearch:
  config:
    files:
      elastic-search-config.yaml:
      queries:
      - name: "list429"
        elasticIndex: "istio-system-istio-system"
        elasticFieldtoSearch: "geoip"
        queryFile: "/etc/config/queryElastic429.json"
      - name: "BlockGCP"
        elasticIndex: "istio-system-istio-system"
        elasticFieldtoSearch: "geoip"
        queryFile: "/etc/config/queryElasticCityOrg.json"

        
  query:
    files:
      queryElastic429.json: |
        {
         "query":{
            "bool":{
               "filter":[
                  {
                     "term":{
                        "kubernetes.namespace":{
                           "value":"istio-system"
                        }
                     }
                  },
                  {
                     "match_phrase":{
                        "response_code":"429"
                     }
                  },
                  {
                     "range":{
                        "start_time":{
                           "gt":"now-5m"
                        }
                     }
                  }
               ]
            }
          }
        }
      queryElasticCityOrg.json: |
        {
        	"query": {
        		"bool": {
        			"filter": [{
        					"term": {
        						"kubernetes.namespace": {
        							"value": "istio-system"
        						}
        					}
        				},
        				{
        					"match_phrase": {
        						"geoip.as_org": "GOOGLE-CLOUD-PLATFORM"
        					}
        				},
        				{
        					"range": {
        						"start_time": {
        							"gt": "now-5m"
        						}
        					}
        				},
        				{
        					"term": {
        						"kubernetes.namespace": {
        							"value": "istio-system"
        						}
        					}
        				},
        				{
        					"match_phrase": {
        						"geoip.city_name": "Groningen"
        					}
        				},
        				{
        					"range": {
        						"start_time": {
        							"gt": "now-5m"
        						}
        					}
        				}
        			]
        		}
        	}
        }
  address: "https://host.docker.internal:9200"

GCPArmor:
  files:
    gcp-armor-config.yaml:
      preview: "true"
      action: "deny(403)"


secrets:
  Opaque:
    elastic-credentials:
      username: xxx
      password: xxx
    google-credentials:
      credentials.json: |-
    elastic-ca-cert:
      cacert.pem: |-
