apiVersion: v1
data:
{{- range $key, $value := .Values.GCPArmor.files }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- end }}
  kind: ConfigMap
metadata:
  name: gcp-armor-config
---
