apiVersion: v1
data:
{{- range $key, $value := .Values.elasticSearch.config.files }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | nindent 4 }}
{{- end }}
kind: ConfigMap
metadata:
  name: elastic-search-config
---
