apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ip-blocker.fullname" . }}
  labels:
      {{- include "ip-blocker.labels" . | nindent 6 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app: ip-blocker
      {{- include "ip-blocker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: ip-blocker
        {{- include "ip-blocker.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - command:
        - /ip-blocker
        image: {{ include "ip-blocker.image" . }}
        name: ip-blocker
{{- if .Values.args }}
        args:
{{ toYaml .Values.args | indent 10 }}
{{- end }}
        env:
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: username
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: password
        - name: ELASTIC_ADDRESS
          value: {{ .Values.elasticSearch.address }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/private_key
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: credentials
          mountPath: /secrets
        - name: commonconfig-volume
          mountPath: /etc/config
{{- if ne (len .Values.extraVolumeMounts) 0 }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
      - name: credentials
        secret:
          secretName: ip-blocker-key
      - name: commonconfig-volume
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: query-elastic
          - configMap:
              name: elastic-search-config
          - configMap:
              name: gcp-armor-config
{{- if ne (len .Values.extraVolumes) 0 }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
